default: &default
  encoding: utf8
  pool: 20

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima-46297_rails7_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima-46297_rails7_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>